##
## EPITECH PROJECT, 2021
## B-AIA-500-PAR-5-1-gomoku-sitpi-kevin.rajendran
## File description:
## Makefile
##

NAME	=	pbrain-gomoku-ai

all: $(NAME)

$(NAME):
	cp main.py $(NAME)
	chmod +x $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
